CREATE TABLE [dbo].[tblSelectVaccineGroupNames](
	[SelectVaccineGroupId] [int] IDENTITY(1,1) NOT NULL,
	[VaccineAbbreviation] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SelectVaccineGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]