CREATE TABLE [dbo].[tblSelectMedicalConditions](
	[SelectMedicalConditionId] [int] IDENTITY(1,1) NOT NULL,
	[MedicalConditionName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SelectMedicalConditionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]