CREATE TABLE [dbo].[tblSelectVaccineNames](
	[SelectVaccineNameID] [int] IDENTITY(1,1) NOT NULL,
	[VaccineName] [varchar](100) NOT NULL,
[VaccineGroup] VARCHAR(30) NULL, 
    PRIMARY KEY CLUSTERED 
(
	[SelectVaccineNameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
