CREATE TABLE [dbo].[tblSelectTestTypes](
	[SelectTestTypeId] [int] IDENTITY(1,1) NOT NULL,
	[TestTypeName] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SelectTestTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]