CREATE TABLE [dbo].[tblSelectManufacturers](
	[SelectManufacturerId] [int] NOT NULL,
	[ManufacturerName] [varchar](60) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SelectManufacturerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]